lmsgovt/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('applogin/', include('applogin.urls')),
    path('teacherhome/', include('teacherhome.urls')),
    path('adminhome/', include('adminhome.urls')),
    path('principalhome/', include('principalhome.urls')),
    path('studenthome/', include('studenthome.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studenthome/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'studenthome'

urlpatterns = [
    url(r'^$', views.TeacherhomepageView.as_view(), name='studenthome'),
    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
   
    url(r'allassignment/$', views.AssignmentView.as_view(), name='allassignment'),
    url(r'currentassignment/$', views.CurrentassignmentView.as_view(), name='currentassignment'),

    url(r'view_marks/$', views.MarksView.as_view(), name='view_marks'),
    
    url(r'announcement/$', views.AnnouncementView.as_view(), name='announcement'),
    path('announcement/<slug:announcement>/', views.AnnouncementDetailView.as_view(), name='announcement_detail'),
    
    url(r'attendance/$', views.AttendanceView.as_view(), name='attendance'),
]

studenthome/models.py
from django.db import models

# Create your models here.

studenthome/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic, View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from django.http import Http404
import os

# from django.contrib.auth.models import User
from applogin.models import User

from adminhome.models import Teacher, School, Student, Principal
from teacherhome.models import Attendance, Assignment, Marksdetails
from principalhome.models import Announcement

from time import gmtime, strftime
import datetime
import mimetypes

#show pdf
from django.contrib import messages
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
import os
from django.conf import settings

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

decorators = [cache_control(no_cache=True, must_revalidate=True, no_store=True), login_required(login_url='http://192.168.2.225:1207/lms/applogin/')]

@method_decorator(decorators, name='dispatch') #if you go back after login it will give error
class TeacherhomepageView(View):
    template_name = 'studenthome/homepage.html'
    
    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            student = Student.objects.get(user = current_user) 

            name = str(student.first_name)+' '+str(student.last_name)
            enrolment_no = student.enrolment_no
            roll_no = student.roll_no
            date_of_birth = student.date_of_birth
            email = student.email
            address = student.address
            study = student.study

            bundle = {'Name':name, 'Enrolment no.': enrolment_no, 'Roll no.':roll_no, 'class': study,  'Date of Birth':date_of_birth, 'Email': email, 'Address': address}
            return render(request, self.template_name, {'student':bundle}) 
            
@method_decorator(decorators, name='dispatch')
class AttendanceView(View):
    template_name = 'studenthome/attendance.html'

    def get(self, request):
        current_user = request.user
        student = Student.objects.get(user = current_user) 
        attendance = Attendance.objects.filter(school = student.school, roll_no = student.roll_no, study = student.study)
        return render(request, self.template_name, {'attendance': attendance})

class MarksView(View):
    template_name = 'studenthome/marks_view.html'

    def get(self, request):
        current_user = request.user
        student = Student.objects.get(user = current_user) 
        try:
            teacher = Teacher.objects.get(class_teacher_of = student.study, school = student.school)  
            marksheets = Marksdetails.objects.filter(roll_no = student.roll_no, teacher = teacher)
        except:
            marksheets=[]
            pass
        bundle = dict()
        key = 1
        for a in marksheets:
            bundle[key] = a
            key += 1 
        return render(request, self.template_name, {'marksheets': bundle})

@method_decorator(decorators, name='dispatch')
class AssignmentView(View):
    template_name = 'studenthome/all_assignment.html'

    def get(self, request):
        current_user = request.user
        student = Student.objects.get(user = current_user) 
        current_date = datetime.date.today()
        assign = Assignment.objects.filter(school = student.school, class_number = student.study, due_date__lte  = current_date).order_by('-due_date')
        bundle=dict()
        key = 1
        for a in assign:
            bundle[key] = a
            key += 1 
        return render(request, self.template_name, {'bundle': bundle})

# For current pending assignments
@method_decorator(decorators, name='dispatch')
class CurrentassignmentView(View):
    template_name = 'studenthome/current_assignment.html'

    def get(self, request):
        current_user = request.user
        student = Student.objects.get(user = current_user)
        current_date = datetime.date.today()
        
        current_assign = Assignment.objects.filter(school = student.school, class_number = student.study, due_date__gte  = current_date).order_by('due_date')

        bundle=dict()
        key = 1
        for a in current_assign:
            bundle[key] = a
            key += 1 
        return render(request, self.template_name, {'bundle': bundle})

@method_decorator(decorators, name='dispatch')      
class LogoutView(View):
    template_name = 'applogin/login.html'

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('applogin:login'))

@method_decorator(decorators, name='dispatch')
class AnnouncementView(View):
    template_name = 'studenthome/announcements.html'

    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            # student = Student.objects.get(user = current_user)
            current_date = datetime.date.today()
            announcement_type1 = Announcement.objects.filter(audience="Students", expiry_date__gte = current_date)
            announcement_type2 = Announcement.objects.filter(audience="All", expiry_date__gte = current_date)
            
            announcements = announcement_type1 | announcement_type2

            return render(request, self.template_name, {'announcements': announcements})

@method_decorator(decorators, name='dispatch')
class AnnouncementDetailView(View):
    template_name = 'studenthome/announcement_detail.html'

    def get(self, request, announcement):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            school = request.user.school
            principal = Principal.objects.get(school = school)
           
            announcement1 = Announcement.objects.get(announcer = principal, audience="Students")
            announcement2 = Announcement.objects.get(announcer = principal, audience="All")
            announcement = announcement1 | announcement2

            return render(request, self.template_name, {'announcement': announcement})

def index(request):
    text = request.GET.get("name")
    return text

studenthome/templates/studenthome/all_assignment.html
{% extends 'studenthome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Previous Assignments</h1>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
    {% if bundle %}
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Sno.</th>
                    <th class="text-center text-uppercase">Class</th>
                    <th class="text-center text-uppercase">Subject</th>
                    <th class="text-center text-uppercase">Due Date</th>
                    <th class="text-center text-uppercase">Assignment</th>
                </tr>
            </thead>
            <tbody>
                <tbody>
                    {% for key, a_value in bundle.items %}
                    <tr>
                        <td>{{ key }}</a></td>
                        <td>{{ a_value.class_number }}</a></td>
                        <td>{{ a_value.subject }}</td>
                        <td>{{ a_value.due_date }}</td>
                        
                        <td><a href="{{ a_value.assignment_file.url }}" target="_new">View Assignment</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </tbody>
        </table>
    {% else %}
        <div class="card" style="padding: 1cm">
            <div class="card-header">
                <h2>You have not any assignment yet!</h2>
            </div>
        </div>
    {% endif %}
    </div>
</div>

{% endblock %}

studenthome/templates/studenthome/announcement_detail.html
{% extends 'studenthome/base.html' %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Announcements</h1>
            <h4>Message</h4>
    </div>
</div>
<div class="container">
    {% if announcements %}
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Message</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ announcement.message }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
</div>

{% endblock %}

studenthome/templates/studenthome/announcements.html
{% extends 'studenthome/base.html' %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Announcements</h1>
    </div>
</div>
<div class="container">
    {% if announcements %}
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Subject</th>
                        <th class="text-center text-uppercase">Audience</th>
                    </tr>
                </thead>
                <tbody>
                    {% for announcement in announcements %}
                        <tr>
                            <td><a href="#">{{ announcement }}</a></td>
                            <td>{{ announcement.audience }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No announcements for you yet.</p>
    {% endif %}
</div>

{% endblock %}

studenthome/templates/studenthome/attendance.html
{% extends 'studenthome/base.html' %}

{% block body %}
{% if attendance%}
    <div style="padding-top: 10px; padding-bottom: 10px">
        <div class="container" style=" height: 120px; background-color: lightcyan">
                <h1>Your are absent on dates</h1>
                
        </div>
    </div>

    <div class="container">

        <div class="col-sm-offset-1 col-sm-8">
        
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tbody>
                        {% for i in attendance %}
                            <tr>
                                <td>{{ i.absent_on }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </tbody>
            </table>
        
        </div>
    </div>
{% else %}
    <div class="card" style="padding: 1cm">
        <div class="card-header">
            <h2>You are not absent yet!</h2>
        </div>
    </div>
{% endif %}
{% endblock %}

studenthome/templates/studenthome/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}LMS{% endblock %}</title>
        
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'applogin/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        
        {% block head %}
        {% endblock %}

    </head>
    <body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'studenthome:studenthome'%}">App</a>
            </div>
    
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'studenthome:studenthome'%}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'studenthome:currentassignment'%}">
                            <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp;View Assignments
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'studenthome:announcement'%}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;View Notifications
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'studenthome:attendance'%}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;View Attendance
                        </a>
                    </li>
                    
                    <li class="">
                        <a href="{% url 'studenthome:view_marks'%}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;View Marksheet
                        </a>
                    </li>
                </ul>
                
    
    
                <ul class="nav navbar-nav navbar-right">
                    {% comment %} <li class="dropdown">
                        <a href="{% url 'studenthome:studenthome'%}" class="dropdown-toggle" data-toggle="dropdown">&nbsp;<span class="glyphicon glyphicon-user"></span> My Profile <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'studenthome:studenthome'%}">Profile</a>
                            </li>
                        </ul>
                    </li> {% endcomment %}
                    <li class="">
                        <a href="{% url 'studenthome:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
    
            </div>
        </div>
    </nav>
        
    {% block body %}
    {% endblock %}
    
    </body>
</html>

studenthome/templates/studenthome/current_assignment.html
{% extends 'studenthome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Due Assignment</h1>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-3 col-sm-8 text-right">
        <a href="{% url 'studenthome:allassignment' %}">Previous Assignments</a>
    </div>
    <div class="col-sm-offset-1 col-sm-8">
    {% if bundle %}
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Sno.</th>
                    <th class="text-center text-uppercase">Class</th>
                    <th class="text-center text-uppercase">Subject</th>
                    <th class="text-center text-uppercase">Due Date</th>
                    <th class="text-center text-uppercase">Assignment</th>
                </tr>
            </thead>
            <tbody>
                <tbody>
                    {% for key, a_value in bundle.items %}
                        <tr>
                            <td>{{ key }}</a></td>
                            <td>{{ a_value.class_number }}</a></td>
                            <td>{{ a_value.subject }}</td>
                            <td>{{ a_value.due_date }}</td>
                            <td><a href="{{ a_value.assignment_file.url }}" target="_new">View Assignment</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </tbody>
        </table>
    {% else %}
        <div class="card" style="padding: 1cm">
            <div class="card-header">
                <h2>You have not any assignment yet!</h2>
            </div>
        </div>
    {% endif %}
    </div>
</div>

{% endblock %}

studenthome/templates/studenthome/homepage.html
{% extends 'studenthome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>{{ student.Name }}</h1>
            <h4>Profile details informations</h4>
    </div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-sm-offset-1 col-sm-8">     
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Stats</th>
                        <th class="text-center text-uppercase">Detail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for key, value in student.items %}
                        <tr>
                            <td>{{ key }}</td>
                            <td>{{ value }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>  
        </div>
    </form>
</div> 
{% endblock %}

studenthome/templates/studenthome/marks_view.html
{% extends 'studenthome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Marksheet</h1>
            <h4>List of Marksheets</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
    {% if marksheets%}
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Sno.</th>
                    <th class="text-center text-uppercase">Roll Number</th>
                    <th class="text-center text-uppercase">Name</th>
                    <th class="text-center text-uppercase">Date</th>
                    <th class="text-center text-uppercase">Marksheet</th>
                </tr>
            </thead>
            <tbody>
                
                {% for key, a_value in marksheets.items %}
                    <tr>
                        <td>{{ key }}</a></td>
                        <td>{{ a_value.roll_no }}</a></td>
                        <td>{{ a_value.name }}</td>
                        <td>{{ a_value.date }}</td>
                        <td><a href="{{ a_value.marksheet_file.url }}" target="_new">View marksheet</a></td>
                        </object></td>
                        
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <div class="card" style="padding: 1cm">
            <div class="card-header">
                <h2>You have not any marksheet yet!</h2>
            </div>
        </div>
    {% endif %}
</div>


{% endblock %}

studenthome/templates/studenthome/notification.html
{% extends 'studenthome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Notifications</h1>
            <h4>See details of notification</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Date</th>
                    <th class="text-center text-uppercase">Notification</th>
                </tr>
            </thead>
            <tbody>
                <tbody>
                    {% for date, notification in Notification.items %}
                        <tr>
                            <td><a href="#">{{ date }}</a></td>
                            <td>{{ notification }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}