adminhome/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'adminhome'
# prefix = '<slug:username>/'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), name='homepage'),
    # path(prefix, views.HomepageView.as_view(), name='homepage'),
    url(r'registerSchool/$', views.RegisterschoolFormView.as_view(), name='registerSchool'),
    url(r'students/$', views.StudentView.as_view(), name='students'),
    url(r'students/addstudent/$', views.AddstudentFormView.as_view(), name='addstudent'),
    path('students/<slug:clss>/', views.StudentIndexView.as_view(), name='class_students'),
    path('students/<slug:clss>/<slug:enrolment_no>/', views.StudentDetailView.as_view(), name='students_detail'),
    url(r'teachers/$', views.TeacherView.as_view(), name='teachers'),
    url(r'teachers/addteacher/$', views.AddteacherFormView.as_view(), name='addteacher'),
    path('teachers/<slug:username>/', views.TeacherDetailView.as_view(), name='teachers_detail'),
    url(r'principal/$', views.PrincipalView.as_view(), name='principal'),
    url(r'principal/addPrincipal/$', views.AddprincipalFormView.as_view(), name='addPrincipal'),
    url(r'circulars/$', views.FeeCircularsView.as_view(), name='feecirculars'),
    url(r'circulars/addcircular/$', views.AddFeeCircularView.as_view(), name='addFeeCircular'),
]

applogin/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'applogin'

urlpatterns = [
    url(r'^$', views.LoginFormView.as_view(), name='login'),
    url(r'register/$', views.RegistrationFormView.as_view(), name='register'),
    url(r'regsuccess/$', views.RegistrationSuccessView.as_view(), name='successful_reg'),
    url(r'password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
]

lmsgovt/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('applogin/', include('applogin.urls')),
    path('teacherhome/', include('teacherhome.urls')),
    path('adminhome/', include('adminhome.urls')),
    path('principalhome/', include('principalhome.urls')),
    path('studenthome/', include('studenthome.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminhome/forms.py
# from django.contrib.auth.models import User

from applogin.models import User

from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import School, Student, Teacher, Principal
from phonenumber_field.formfields import PhoneNumberField

class RegisterschoolForm(forms.ModelForm):
    school_name = forms.CharField(max_length=500)
    class_upto = forms.IntegerField(min_value=5, max_value=12)
    address = forms.Textarea()
    city = forms.CharField(max_length = 50)
    district = forms.CharField(max_length = 50)
    state = forms.CharField(max_length = 50)
    # filling address fields based on pincode
    pincode = forms.IntegerField(min_value=100000, max_value=999999)

    class Meta:
        model = School
        fields = ['school_name', 'class_upto', 'address', 'city', 'district', 'state', 'pincode']

class AddstudentForm(forms.ModelForm):
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    date_of_birth = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    admission_date = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    email = forms.EmailInput()
    address = forms.Textarea()
    study = forms.IntegerField(max_value=12, min_value=1)

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'date_of_birth', 'admission_date', 'email', 'address', 'study']

class AddteacherForm(forms.ModelForm):
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    date_of_birth = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    joining_date = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    email = forms.EmailInput()
    address = forms.Textarea()
    phone = PhoneNumberField(widget=forms.TextInput(), required=False)
    is_class_teacher = forms.BooleanField(required=False)
    class_teacher_of = forms.IntegerField(min_value=1, max_value=12, required=False)
    subject = forms.TextInput()
    resume = forms.FileField()

    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'date_of_birth', 'joining_date', 'email', 'address', 'phone', 'is_class_teacher', 'class_teacher_of', 'subject', 'resume']

class AddprincipalForm(forms.ModelForm):
    first_name = forms.TextInput()
    last_name = forms.TextInput()
    date_of_birth = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    joining_date = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    email = forms.EmailInput()
    address = forms.Textarea()
    phone = PhoneNumberField(widget=forms.TextInput(), required=False)
    is_teacher = forms.BooleanField(required=False)
    subject = forms.CharField(required=False)
    resume = forms.FileField()

    class Meta:
        model = Principal
        fields = ['first_name', 'last_name', 'date_of_birth', 'joining_date', 'email', 'address', 'phone', 'is_teacher', 'subject', 'resume']

adminhome/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic, View
from django.http import HttpResponse, HttpResponseRedirect
from .models import LocalAdmin, Student, Teacher, Principal, Parent, School, Feecircular
from .forms import AddstudentForm, AddteacherForm, RegisterschoolForm, AddprincipalForm

# from django.contrib.auth.models import User
from applogin.models import User

from django.http import Http404
from django.core.mail import send_mail, EmailMessage
# from django.contrib import messages

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

from easy_pdf.rendering import render_to_pdf
from django.core.files.base import ContentFile
import datetime

# from django.contrib.auth.mixins import LoginRequiredMixin

from django.template import loader

import string
from random import *
min_char = 8
max_char = 12

decorators = [cache_control(no_cache=True, must_revalidate=True, no_store=True), login_required(login_url='http://185.201.9.188:80/lms/applogin/')]

def createNewUser(email, first_name, last_name, u_type):
    username = email.split('@')[0]

    username = username.replace('.', '-')

    # check for unique username
    similar_users = len(User.objects.filter(username=username))
    if similar_users != 0:
        new_username = username + '_' + str(similar_users)
        i = 0
        while len(User.objects.filter(username=new_username)) != 0:
            i += 1
            new_username = username + '_' + str(similar_users  + i)
        username = new_username

    # generate a random string
    allchar = string.ascii_letters + string.punctuation + string.digits
    password = "".join(choice(allchar) for x in range(randint(min_char, max_char)))

    new_user = User(username=username, email=email, first_name=first_name, last_name=last_name)
    new_user.set_password(password)
    new_user.user_type = u_type
    new_user.save()

    return new_user, username

def sendSetPasswordMail(request, new_user, first_name, username, current_user, email):

    current_site = get_current_site(request)
    domain = current_site.domain
    uid = urlsafe_base64_encode(force_bytes(new_user.pk)).decode()
    token = default_token_generator.make_token(new_user)
    protocol = 'http'

    if type(token) != str:
        token = token[0]

    html_message = loader.render_to_string(
    'adminhome/user_registration_email.html',
    {
        'name': first_name,
        'username': username,
        'protocol': protocol,
        'domain':  domain,
        'uid': uid,
        'token': token
    })

    # print(html_message)

    # re-configure connection/email backend dynamically!

    send_mail(
        'Account Registration',
        '',
        str(current_user),
        [email],
        fail_silently=False,
        html_message=html_message
    )

def sendFeeReminderMail(current_user, fee_obj, fileData):

    sch_obj = current_user.school
    students = Student.objects.filter(school=sch_obj)

    mailing_list = []
    for s in students:
        mailing_list.append(s.email)

    draft_email = EmailMessage(
        'Reminder for Fee Payment',
        'Please find attached the fee circular for this academic year. For fee payment and related queries, please visit the admin office. Please ignore if the fees has already been paid.',
        str(current_user),
        mailing_list,
    )

    draft_email.attach(fee_obj.file_name, fileData, 'application/pdf')
    draft_email.send()

@method_decorator(decorators, name='dispatch')
class HomepageView(View):
    template_name = 'adminhome/homepage.html'

    # def get(self, request, username):
    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            school = School.objects.get(school_admin=current_user)

            if school.is_registered is True:
                students = len(Student.objects.filter(school=school))
                teachers = len(Teacher.objects.filter(school=school))
                bundle = {'user':current_user, 'school':str(school), 'students':students, 'teachers':teachers}
                return render(request, self.template_name, {'bundle': bundle})
            else:
                return redirect('adminhome:registerSchool')

@method_decorator(decorators, name='dispatch')
class RegisterschoolFormView(View):
    form_class = RegisterschoolForm
    template_name = 'adminhome/registerschool_form.html'

    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})

    def post(self, request):
        current_user = request.user
        form = self.form_class(request.POST)

        if form.is_valid():
            school_name = form.cleaned_data['school_name']
            class_upto = form.cleaned_data['class_upto']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            district = form.cleaned_data['district']
            state = form.cleaned_data['state']
            pincode = form.cleaned_data['pincode']

            try:
                old_school = School.objects.get(school_name=school_name, class_upto=class_upto, address=address, city=city, district=district, state=state, pincode=pincode)
                form.add_error('school_name', 'School already exists. Current Admin: ' + str(old_school.school_admin))
            except:
                school = School.objects.get(school_admin=current_user.pk)
                school.school_name = school_name
                school.class_upto = class_upto
                school.address= address
                school.city = city
                school.district = district
                school.state = state
                school.pincode = pincode
                school.is_registered = True
                school.has_principal = False

                school.save()

                return redirect('adminhome:homepage')

        return render(request, self.template_name, {'form': form})

@method_decorator(decorators, name='dispatch')
class StudentView(View):
    template_name = 'adminhome/students.html'

    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            school = School.objects.get(school_admin=current_user)

            NC = school.class_upto
            bundle = dict()

            for c in range(1, NC+1):
                clss = 'Class_' + str(c)
                school_students = Student.objects.filter(school=school)
                class_count = len(school_students.filter(study=c))
                bundle[clss] = class_count

            return render(request, self.template_name, {'class_dict': bundle})

@method_decorator(decorators, name='dispatch')
class AddstudentFormView(View):
    form_class = AddstudentForm
    template_name = 'adminhome/addstudent_form.html'

    # displays a blank form
    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            form = self.form_class(None)
            return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        current_user = request.user

        if form.is_valid():
            student = form.save(commit=False)

            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            study = form.cleaned_data['study']
            date_of_birth = form.cleaned_data['date_of_birth']
            admission_date = form.cleaned_data['admission_date']

            if admission_date <= date_of_birth:
                form.add_error('admission_date', 'Admission date can\'t be earlier than DOB.')
            else:
                new_user, username = createNewUser(email, first_name, last_name, 1)

                school = School.objects.get(school_admin=current_user)
                prefix = str(form.cleaned_data['admission_date'])[:4]

                all_students = len(Student.objects.filter(school=school).filter(enrolment_no__startswith=prefix))
                enrolment_no = prefix + '' + str(all_students + 1)
                student.enrolment_no = enrolment_no
                student.school = school
                student.user = new_user

                s_roll =  ""
                s_roll = s_roll + str(study)
                no_student = len(Student.objects.filter(school = school, study= study))  + 1
                student.roll_no = s_roll + str(no_student)

                student.save()
                sendSetPasswordMail(request, new_user, first_name, username, current_user, email)
            
                return redirect('adminhome:students')

        return render(request, self.template_name, {'form': form})

@method_decorator(decorators, name='dispatch')
class StudentIndexView(View):
    template_name = 'adminhome/students_index.html'

    def get(self, request, clss):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            school = School.objects.get(school_admin=current_user)

            students = Student.objects.filter(school=school)
            cls_no = int(clss[6:])

            class_students = students.filter(study=cls_no)

adminhome/templates/adminhome/addfeecircular_form.html
{% extends 'adminhome/base.html' %}

{% block head %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}
{% block title %}Fee Circular Form{% endblock %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Fee Circular Form</h1>
			<h4>Enter the details to generate circular</h4>
	</div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Category</th>
                        <th class="text-center text-uppercase">Total Fees</th>
                        <th class="text-center text-uppercase">Fees Due</th>
                        <th class="text-center text-uppercase">Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Primary</td>
                        <td><input type="number" name="tfee1" min=0></td>
                        <td><input type="number" name="dfee1" min=0></td>
                        <td><input type="date" name="ddate1"></td>
                    </tr>
                    <tr>
                        <td>Secondary</td>
                        <td><input type="number" name="tfee2" min=0></td>
                        <td><input type="number" name="dfee2" min=0></td>
                        <td><input type="date" name="ddate2"></td>
                    </tr>
                    <tr>
                        <td>Sr. Secondary</td>
                        <td><input type="number" name="tfee3" min=0></td>
                        <td><input type="number" name="dfee3" min=0></td>
                        <td><input type="date" name="ddate3"></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-sm-offset-1 col-sm-8">
            <b>Notes:</b><br>
            <textarea rows="5" cols="80" name="notes"></textarea>
        </div>
        <div class="col-sm-offset-4 col-sm-8" style="padding-top: 10px">
            <button type="submit" class = "btn btn-success">Generate PDF</button>
        </div>
    </form>
</div>


{% endblock %}

adminhome/templates/adminhome/addprincipal_form.html
{% extends 'adminhome/base.html' %}
{% block head %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}
{% block title %}Principal Registration{% endblock %}

{% block body %}

<script>
    $(function () {
        var today = new Date();
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD',
            maxDate: today
        });
    });
</script>

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Principal Registration</h1>
			<h4>Enter the details to add principal to the database</h4>
	</div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid">
            {% include 'adminhome/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-1">
                    <button type="submit" class="btn btn-success">Register</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

adminhome/templates/adminhome/addteacher_form.html
{% extends 'adminhome/base.html' %}
{% block head %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}
{% block title %}Teacher Registration{% endblock %}

{% block body %}

<script>
    $(function () {
        var today = new Date();
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD',
            maxDate: today
        });
    });
</script>

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Teacher Registration</h1>
			<h4>Enter the details to add teacher to the database</h4>
	</div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid">
            {% include 'adminhome/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-1">
                    <button type="submit" class="btn btn-success">Register</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

adminhome/templates/adminhome/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}LMS{% endblock %}</title>
        
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'applogin/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        
        {% block head %}
        {% endblock %}

    </head>
    <body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'adminhome:homepage' %}">App</a>
            </div>
    
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'adminhome:homepage' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'adminhome:students' %}">
                            <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Students
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'adminhome:teachers' %}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Teachers
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'adminhome:principal' %}">
                            <span class="glyphicon glyphicon-king" aria-hidden="true"></span>&nbsp; Principal
                        </a>
                    </li>
                </ul>
                
                <!-- <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form> -->
    
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">&nbsp;<span class="glyphicon glyphicon-plus"></span> Options <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'adminhome:feecirculars' %}"><span class="glyphicon glyphicon-usd"></span>&nbsp;Fee Circulars</a>
                            </li>
                            <!-- <li>
                                <a href="#">Option1</a>
                            </li>
                            <li>
                                <a href="#">Option1</a>
                            </li> -->
                        </ul>
                    </li>
                    <li class="">
                        <a href="{% url 'applogin:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
    
            </div>
        </div>
    </nav>
        
    {% block body %}
    {% endblock %}
    
    </body>
</html>

adminhome/templates/adminhome/feecirculars.html
{% extends 'adminhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
        <h1>Fee Circulars</h1>
        <h4>Overview</h4>
    </div>
</div>

<div class="container">
    <div class="col-lg-offset-10 col-lg-2" style="padding: 20px">
        <a href="{% url 'adminhome:addFeeCircular' %}">Add Circular</a>
    </div>
    <div class="col-sm-offset-1 col-sm-8">
        {% if bundle %}
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Ref. No.</th>
                        <th class="text-center text-uppercase">Date</th>
                        <th class="text-center text-uppercase">Link</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in bundle %}
                        <tr>
                            <td>{{ obj.ref_no }}</td>
                            <td>{{ obj.date_of_issue }}</td>
                            <td><a href="{{ obj.pdf_ver.url }}" download="{{ obj.file_name }}">Download</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No circulars added yet.</p>
        {% endif %}
    </div>

</div>

{% endblock %}

adminhome/templates/adminhome/students.html
{% extends 'adminhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Students</h1>
            <h4>Class-wise list of students currently registered</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-3 col-sm-8 text-right">
        <a href="{% url 'adminhome:addstudent' %}">Add Student</a>
    </div>
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Class</th>
                    <th class="text-center text-uppercase"># Students</th>
                </tr>
            </thead>
            <tbody>
                {% for clss, count in class_dict.items %}
                    <tr>
                        <td><a href="{% url 'adminhome:class_students' clss %}">{{ clss }}</a></td>
                        <td>{{ count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

adminhome/templates/adminhome/students_index.html
{% extends 'adminhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>{{ clss }}</h1>
            <h4>.....</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Name</th>
                    <th class="text-center text-uppercase"> Enrolment No. </th>
                </tr>
            </thead>
            <tbody>
                {% for student in class_students %}
                    <tr>
                        <td><a href="{% url 'adminhome:students_detail' clss student.enrolment_no %}">{{ student }}</a></td>
                        <td>{{ student.enrolment_no }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

adminhome/templates/adminhome/teachers.html
{% extends 'adminhome/base.html' %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Teachers</h1>
            <h4>List of teachers currently registered</h4>
    </div>
</div>
<div class="container">
    {% if teachers %}
        <div class="col-sm-offset-3 col-sm-8 text-right">
            <a href="{% url 'adminhome:addteacher' %}">Add Teacher</a>
        </div>
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Name</th>
                        <th class="text-center text-uppercase">Subject</th>
                    </tr>
                </thead>
                <tbody>
                    {% for teacher in teachers %}
                        <tr>
                            <td><a href="{% url 'adminhome:teachers_detail' teacher.user.username %}">{{ teacher }}</a></td>
                            <td>{{ teacher.subject }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No teachers registered yet. Click <a href="{% url 'adminhome:addteacher' %}">here</a> to add teacher.</p>
    {% endif %}
</div>

{% endblock %}

adminhome/templates/adminhome/user_registration_email.html
{% autoescape off %}

<p>Hi {{ name }}! Your account has been created with the following username: <b>{{ username }}</b>.</p> 

<p>To complete the registration process for your account, you must set a password for your account. Please click the link below for setting up a new password:</p>

<p>{{ protocol }}://{{ domain }}{% url 'applogin:password_reset_confirm' uidb64=uid token=token %}</p>

<p>If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.</p>

<p>Sincerely,</p>
<p>Dev Team</p>

{% endautoescape %}