applogin/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'applogin'

urlpatterns = [
    url(r'^$', views.LoginFormView.as_view(), name='login'),
    url(r'register/$', views.RegistrationFormView.as_view(), name='register'),
    url(r'regsuccess/$', views.RegistrationSuccessView.as_view(), name='successful_reg'),
    url(r'password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
]

lmsgovt/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('applogin/', include('applogin.urls')),
    path('teacherhome/', include('teacherhome.urls')),
    path('adminhome/', include('adminhome.urls')),
    path('principalhome/', include('principalhome.urls')),
    path('studenthome/', include('studenthome.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applogin/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

import unicodedata

from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.hashers import (
    UNUSABLE_PASSWORD_PREFIX, identify_hasher,
)

# from django.contrib.auth.models import User

from django.conf import settings

from .models import User

from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.text import capfirst
from django.utils.translation import gettext, gettext_lazy as _

UserModel = get_user_model()


class LoginForm(forms.Form):
	username = forms.CharField(max_length=50)
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password']

class RegistrationForm(UserCreationForm):
	first_name = forms.CharField(max_length=50)
	last_name = forms.CharField(max_length=50)
	email = forms.CharField(widget=forms.EmailInput)
	username = forms.CharField(max_length=50)

	class Meta:
		model = User
		fields = [ "first_name", "last_name", "email", "username"]

class RequestpwdForm(forms.ModelForm):
	email = forms.CharField(widget=forms.EmailInput)

	class Meta:
		model = User
		fields = ['email']

class ResetpwdForm(forms.Form):
	username = forms.CharField(max_length=50)
	password = forms.CharField(widget=forms.PasswordInput)
	password_confirmation = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password', 'password_confirmation']

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        #Check if user (email) exists in DB

        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = UserModel._default_manager.filter(**{
            '%s__iexact' % UserModel.get_email_field_name(): email,
            'is_active': True,
        })
        return (u for u in active_users if u.has_usable_password())

    def save(self, domain_override=None,
             subject_template_name='applogin/password_reset_subject.txt',
             email_template_name='applogin/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name=None,
             extra_email_context=None):
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        email = self.cleaned_data["email"]
        for user in self.get_users(email):
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            context = {
                'email': email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
                **(extra_email_context or {}),
            }
            self.send_mail(
                subject_template_name, email_template_name, context, from_email,
                email, html_email_template_name=html_email_template_name,
            )


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

applogin/views.py
from django.views import View
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse
from django import forms

from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
)

from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url, urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from urllib.parse import urlparse, urlunparse

from .forms import LoginForm, RequestpwdForm, ResetpwdForm, RegistrationForm, PasswordResetForm, SetPasswordForm
from adminhome.models import School
from .models import User

UserModel = get_user_model()

class LoginFormView(View):
    form_class = LoginForm
    template_name = 'applogin/login_form.html'

    # displays a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
                                   
    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        # determine which radio button is selected
        radio_btn = request.POST.get('radio_btn')

        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # returns user objects if credentials are correct

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active and int(radio_btn) == user.user_type:
                    login(request, user)
                    # redirect to respective page
                    if radio_btn == '1':
                        return redirect('studenthome:studenthome')
                    elif radio_btn == '2':
                        return redirect('teacherhome:teacher_homepage')
                    elif radio_btn == '3':
                        return redirect('principalhome:homepage')
                    else:
                        return redirect('adminhome:homepage')
                    # Add else condition
                        # return HttpResponseRedirect(reverse('adminhome:homepage', args=(username,)))
                else:
                    form.add_error('username', "User does not exist.")
            else:
                form.add_error('username', "User credentials did not match existing records.")

        return render(request, self.template_name, {'form': form})

def checkExistingUsers(email):
    try:
        User.objects.get(email=email)
        return True
    except:
        return False

class RegistrationFormView(View):
    form_class = RegistrationForm
    template_name = 'applogin/registration_form.html'
    
    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #put data inside blank text fields 
    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            form_obj = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            confpwd = form.cleaned_data['password2']
            email = form.cleaned_data['email']

            if password == confpwd:
                flag = checkExistingUsers(email)
                if flag == False:
                    form_obj.save()

                    user = User.objects.get(username=username)

                    user.user_type = 4
                    user.save()

                    # generate a unique school code as primary key
                    all_schools = School.objects.all()
                    school_code = 'SCH' + '' + str(len(all_schools) + 1)
                    school = School(school_code=school_code, school_admin=user)
                
                    school.save()
                
                    return render(request, 'applogin/registrationsuccess.html', {'form': form})
                else:
                    form.add_error('email', 'A user is already registered with this email.')
            else:
                form.add_error('confirm_password', "Password fields do not match.")

        return render(request, 'applogin/registration_form.html', {'form': form})

class RegistrationSuccessView(View):
    template_name = 'applogin/registrationsuccess.html'

    def get(self, request):
        return render(request, self.template_name)

# Class-based password reset views
# - PasswordResetView sends the mail
# - PasswordResetDoneView shows a success message for the above
# - PasswordResetConfirmView checks the link the user clicked and
#   prompts for a new password
# - PasswordResetCompleteView shows a success message for the above

class PasswordContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title,
            **(self.extra_context or {})
        })
        return context


class PasswordResetView(PasswordContextMixin, FormView):
    template_name = 'applogin/password_reset_form.html'
    email_template_name = 'applogin/password_reset_email.html'
    extra_email_context = None
    form_class = PasswordResetForm
    from_email = None
    html_email_template_name = None
    subject_template_name = 'applogin/password_reset_subject.txt'
    success_url = reverse_lazy('applogin:password_reset_done')
    title = _('Password reset')
    token_generator = default_token_generator

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        opts = {
            'use_https': self.request.is_secure(),
            'token_generator': self.token_generator,
            'from_email': self.from_email,
            'email_template_name': self.email_template_name,
            'subject_template_name': self.subject_template_name,
            'request': self.request,
            'html_email_template_name': self.html_email_template_name,
            'extra_email_context': self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


INTERNAL_RESET_URL_TOKEN = 'set-password'
INTERNAL_RESET_SESSION_TOKEN = '_password_reset_token'


class PasswordResetDoneView(PasswordContextMixin, TemplateView):
    template_name = 'applogin/password_reset_done.html'
    title = _('Password reset sent')


class PasswordResetConfirmView(PasswordContextMixin, FormView):
    template_name = 'applogin/password_reset_confirm.html'
    form_class = SetPasswordForm
    post_reset_login = False
    post_reset_login_backend = None
    success_url = reverse_lazy('applogin:password_reset_complete')
    title = _('Enter new password')
    token_generator = default_token_generator

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        assert 'uidb64' in kwargs and 'token' in kwargs

        self.validlink = False
        self.user = self.get_user(kwargs['uidb64'])

        if self.user is not None:
            token = kwargs['token']
            if token == INTERNAL_RESET_URL_TOKEN:
                session_token = self.request.session.get(INTERNAL_RESET_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                if self.token_generator.check_token(self.user, token):
                    # Store the token in the session and redirect to the
                    # password reset form at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_RESET_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(token, INTERNAL_RESET_URL_TOKEN)
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist, ValidationError):
            user = None
        return user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        del self.request.session[INTERNAL_RESET_SESSION_TOKEN]
        if self.post_reset_login:

applogin/templates/applogin/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}LMS{% endblock %}</title>
        
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine"/>
        <link rel="stylesheet" type="text/css" href="{% static 'applogin/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        
    </head>
    <body>
        
    {% block body %}
    {% endblock %}
    
    </body>
</html>

applogin/templates/applogin/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-3">{{ field.label_tag }}</label>
		<div class="col-sm-9">{{ field }}</div>
	</div>

{% endfor %}

applogin/templates/applogin/login_form.html
{% extends 'applogin/base.html' %}
{% block title %}Welcome{% endblock %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>App</h1>
			<h4>Enter your credentials below</h4>
	</div>
</div>

<div class="container">
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="container-fluid">
			<div class="col-lg-offset-5 col-sm-7" style="padding: 20px">
				<a href="{% url 'applogin:register' %}">Register here</a>
			</div>
			{% include 'applogin/form-template.html' %}
			<div class="col-xs-offset-2 col-xs-10" style="padding: 10px">
				<div class="form-check">
					<input type="radio" class="form-check-input" id="materialUnchecked" name="radio_btn" value = "1" required>
					<label class="form-check-label" for="materialUnchecked">Student</label>
					<input type="radio" class="form-check-input" id="materialUnchecked" name="radio_btn" value = "2">
					<label class="form-check-label" for="materialUnchecked">Teacher</label>
					<input type="radio" class="form-check-input" id="materialUnchecked" name="radio_btn" value = "3">
					<label class="form-check-label" for="materialUnchecked">Principal</label>
					<input type="radio" class="form-check-input" id="materialUnchecked" name="radio_btn" value = "4">
					<label class="form-check-label" for="materialUnchecked">Admin</label>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-1">
					<a href="{% url 'applogin:password_reset' %}">Forgot password?</a>
				</div>
				<div class="col-xs-1">
					<button type="submit" class="btn btn-success">Log In</button>
				</div>
			</div>
		</div>
	</form>
</div>


{% endblock %}

applogin/templates/applogin/password_reset.html
{% extends 'applogin/base.html' %}
{% block title %}Password Request{% endblock %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Request Password</h1>
			<h4>Enter registered email address to which the reset link is to be sent</h4>
	</div>
</div>

<div class="container">
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="container-fluid">
			{% include 'applogin/form-template.html' %}
			<div class="form-group text-center">
				<div class="col-xs-offset-3 col-xs-1 ">
					<button type="submit" class="btn btn-warning">Send mail</button>
				</div>
			</div>
		</div>
	</form>
</div>

{% endblock %}

applogin/templates/applogin/password_reset_complete.html
{% extends 'applogin/base.html' %}
{% block title %}Password reset{% endblock %}
{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Password changed Successfully</h1>
	</div>
</div>

<div class="container">
	<div class="container-fluid">
		<div class="col-lg-offset-2 col-sm-10" style="padding: 20px">
			<h4>Password change successful. Click here to <a href="{% url 'applogin:login' %}">login.</a></h4>
		</div>
	</div>
</div>
{% endblock %}

applogin/templates/applogin/password_reset_confirm.html
{% extends 'applogin/base.html' %}

{% block body %}
{% if validlink %}
<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Password Reset</h1>
			<h4>Please enter a new pasword for your account</h4>
	</div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid">
            {% include 'applogin/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-1">
                    <button type="submit" class="btn btn-success">Reset Password</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% else %}
<p>
    The password reset link was invalid, possibly because it has already been used.
    Please request a new password reset.
</p>
{% endif %}
{% endblock %}

applogin/templates/applogin/password_reset_done.html
{% extends 'applogin/base.html' %}
{% block title %}Password Reset{% endblock %}
{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Password Reset Initiated</h1>
	</div>
</div>

<div class="container">
	<div class="container-fluid">
		<div class="col-lg-offset-2 col-sm-10" style="padding: 20px">
			<h4>Password reset link has been send to your email. Please check you mailbox and click on the link to proceed with password reset.</h4>
		</div>
	</div>
</div>
{% endblock %}

applogin/templates/applogin/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your account, click the link below:

{{ protocol }}://{{ domain }}{% url 'applogin:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Dev Team
{% endautoescape %}

applogin/templates/applogin/password_reset_form.html
{% extends 'applogin/base.html' %}
{% block title %}Password Request{% endblock %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Request Password</h1>
			<h4>Enter registered email address to which the reset link is to be sent</h4>
	</div>
</div>

<div class="container">
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="container-fluid">
			{% include 'applogin/form-template.html' %}
			<div class="form-group text-center">
				<div class="col-xs-offset-3 col-xs-1 ">
					<button type="submit" class="btn btn-warning">Send mail</button>
				</div>
			</div>
		</div>
	</form>
</div>

{% endblock %}

applogin/templates/applogin/registration_form.html
{% extends 'applogin/base.html' %}
{% block title %}Registration{% endblock %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
        <h1>Local Admin Registration</h1>
        <h4>Please fill up the form below</h4>
	</div>
</div>

<div class = "container-fluid">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-9">
            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'applogin/form-template.html'%}
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class = "btn btn-success">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

applogin/templates/applogin/registrationsuccess.html
{% extends 'applogin/base.html' %}
{% block title %}Registration Complete{% endblock %}
{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Registered Successfully</h1>
	</div>
</div>

<div class="container">
	<div class="container-fluid">
		<div class="col-lg-offset-2 col-sm-10" style="padding: 20px">
			<h4>Registration successful. Click here to <a href="{% url 'applogin:login' %}">login.</a></h4>
		</div>
	</div>
</div>
{% endblock %}