applogin/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'applogin'

urlpatterns = [
    url(r'^$', views.LoginFormView.as_view(), name='login'),
    url(r'register/$', views.RegistrationFormView.as_view(), name='register'),
    url(r'regsuccess/$', views.RegistrationSuccessView.as_view(), name='successful_reg'),
    url(r'password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'logout/$', views.LogoutView.as_view(), name='logout'),
]

lmsgovt/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('applogin/', include('applogin.urls')),
    path('teacherhome/', include('teacherhome.urls')),
    path('adminhome/', include('adminhome.urls')),
    path('principalhome/', include('principalhome.urls')),
    path('studenthome/', include('studenthome.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

principalhome/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'principalhome'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), name='homepage'),
    url(r'students/$', views.StudentView.as_view(), name='students'),
    path('students/<slug:clss>/', views.StudentIndexView.as_view(), name='class_students'),
    path('students/<slug:clss>/<slug:student>/', views.StudentDetailView.as_view(), name='students_detail'),
    url(r'teachers/$', views.TeacherView.as_view(), name='teachers'),
    path('teachers/<slug:teacher>/', views.TeacherDetailView.as_view(), name='teachers_detail'),
    url(r'announcements/$', views.AnnouncementView.as_view(), name='announcements'),
    url(r'makeAnnouncement/$', views.AnnouncementFormView.as_view(), name='announce'),
]

principalhome/models.py
from django.db import models
from adminhome.models import Principal

class Announcement(models.Model):
    announcer = models.ForeignKey(Principal, on_delete=models.CASCADE)
    subject = models.CharField(max_length = 100)
    announcement_date = models.DateField()
    expiry_date = models.DateField()
    audience = models.CharField(max_length = 20)
    message = models.TextField()

    def __str__(self):
        return self.subject[:20]

principalhome/forms.py
from django import forms
from .models import Announcement

class AnnouncementForm(forms.ModelForm):
    subject = forms.TextInput()
    expiry_date = forms.DateTimeField(widget=forms.TextInput(attrs={'class':'datetime-input'}))
    audience = forms.ChoiceField(choices = [(1, "Teachers"), (2, "Students"), (3, "All")], widget=forms.RadioSelect, required=True)
    message = forms.Textarea()

    class Meta:
        model = Announcement
        fields = ['subject', 'expiry_date', 'audience', 'message']

principalhome/views.py
from django.shortcuts import render, reverse, redirect
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
from adminhome.models import Student, Teacher, Principal, School
from django.http import Http404
from .forms import AnnouncementForm
from .models import Announcement
import datetime

# from django.contrib.auth.mixins import LoginRequiredMixin

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

decorators = [cache_control(no_cache=True, must_revalidate=True, no_store=True), login_required(login_url='http://185.201.9.188:80/lms/applogin/')]

@method_decorator(decorators, name='dispatch')
class HomepageView(View):
    template_name = 'principalhome/homepage.html'

    def get(self, request):
        current_user = request.user
        if str(current_user) is 'AnonymousUser':
            raise Http404
        else:
            principal = Principal.objects.get(user = current_user)
            school = principal.school
            students = len(Student.objects.filter(school=school))
            teachers = len(Teacher.objects.filter(school=school))
            bundle = {'user':current_user, 'school':str(school), 'students':students, 'teachers':teachers}
            return render(request, self.template_name, {'bundle': bundle})

@method_decorator(decorators, name='dispatch')
class StudentView(View):
    template_name = 'principalhome/students.html'

    def get(self, request):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        school = principal.school

        NC = school.class_upto
        bundle = dict()

        for c in range(1, NC+1):
            clss = 'Class_' + str(c)
            school_students = Student.objects.filter(school=school)
            class_count = len(school_students.filter(study=c))
            bundle[clss] = class_count

        return render(request, self.template_name, {'class_dict': bundle})

@method_decorator(decorators, name='dispatch')
class StudentIndexView(View):
    template_name = 'principalhome/students_index.html'

    def get(self, request, clss):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        school = principal.school

        students = Student.objects.filter(school=school)
        cls_no = int(clss[6:])

        class_students = students.filter(study=cls_no)

        return render(request, self.template_name, {'class_students': class_students, 'clss':clss})

@method_decorator(decorators, name='dispatch')
class StudentDetailView(View):
    template_name = 'principalhome/students_detail.html'

    def get(self, request, clss, student):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        school = principal.school
        study = int(clss[6:])
        stud_arr = student.split('-')
        fname = stud_arr[0]
        lname = stud_arr[1]
        student = Student.objects.get(school=school, study=study, first_name=fname, last_name=lname)
        return render(request, self.template_name, {'student':student})    

@method_decorator(decorators, name='dispatch')
class TeacherView(View):
    template_name = 'principalhome/teachers.html'

    def get(self, request):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        school = principal.school

        teachers = Teacher.objects.filter(school=school)

        if len(teachers) > 0:
            return render(request, self.template_name, {'teachers': teachers})

        return render(request, self.template_name)

@method_decorator(decorators, name='dispatch')
class TeacherDetailView(View):
    template_name = 'principalhome/teachers_detail.html'

    def get(self, request, teacher):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        school = principal.school
        name_arr = teacher.split('-')
        fname = name_arr[0]
        lname = name_arr[1]
        teacher = Teacher.objects.get(school=school, first_name=fname, last_name=lname)
        return render(request, self.template_name, {'teacher': teacher})

@method_decorator(decorators, name='dispatch')
class AnnouncementView(View):
    template_name = 'principalhome/announcements.html'

    def get(self, request):
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        current_date = datetime.date.today()
        announcements = Announcement.objects.filter(announcer=principal, expiry_date__gte = current_date).order_by('-expiry_date')
        return render(request, self.template_name, {'announcements': announcements})


@method_decorator(decorators, name='dispatch')
class AnnouncementFormView(View):
    form_class = AnnouncementForm
    template_name = 'principalhome/announcement_form.html'

    # displays a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        current_user = request.user
        principal = Principal.objects.get(user = current_user)
        current_date = datetime.date.today()

        if form.is_valid():
            subject = form.cleaned_data['subject']
            expiry_date = form.cleaned_data['expiry_date']
            audience = form.cleaned_data['audience']
            message = form.cleaned_data['message']

            if audience == "1":
                audience = "Teachers"
            elif audience == "2":
                audience = "Students"
            else:
                audience = "All"

            announcement = Announcement(announcer=principal, subject=subject, announcement_date=current_date, expiry_date=expiry_date, audience=audience, message=message)
            announcement.save()

            return redirect('principalhome:announcements')

        return render(request, self.template_name, {'form': form})

principalhome/templates/principalhome/announcement_form.html
{% extends 'principalhome/base.html' %}
{% block head %}
	<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
	<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
	<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
{% endblock %}
{% block title %}Announcements{% endblock %}

{% block body %}

<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD'
        });
    });
</script>

<div style="padding-top: 10px; padding-bottom: 10px">
	<div class="container" style=" height: 120px; background-color: lightcyan">
			<h1>Announcement Form</h1>
			<h4>Fill in the details to make an announcement</h4>
	</div>
</div>

<div class="container">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container-fluid">
            {% include 'principalhome/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-1">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

principalhome/templates/principalhome/announcements.html
{% extends 'principalhome/base.html' %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Announcements</h1>
            <h4>View previous announcements or make a new announcement</h4>
    </div>
</div>
<div class="container">
    {% if announcements %}
        <div class="col-sm-offset-3 col-sm-8 text-right">
            <a href="{% url 'principalhome:announce' %}">Make Announcement</a>
        </div>
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Subject</th>
                        <th class="text-center text-uppercase">Audience</th>
                    </tr>
                </thead>
                <tbody>
                    {% for a in announcements %}
                        <tr>
                            <td><a href="#">{{ a.subject }}</a></td>
                            <td>{{ a.audience }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No announcements made yet. Click <a href="{% url 'principalhome:announce' %}">here</a> to make an announcement.</p>
    {% endif %}
</div>

{% endblock %}

principalhome/templates/principalhome/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}LMS{% endblock %}</title>
        
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'applogin/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        
        {% block head %}
        {% endblock %}

    </head>
    <body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'principalhome:homepage' %}">App</a>
            </div>
    
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'principalhome:homepage' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'principalhome:students' %}">
                            <span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Students
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'principalhome:teachers' %}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Teachers
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'principalhome:announcements' %}">
                            <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>&nbsp; Announcements
                        </a>
                    </li>
                </ul>
                
                <!-- <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form> -->
    
                <ul class="nav navbar-nav navbar-right">
<!--                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">&nbsp;<span class="glyphicon glyphicon-user"></span> My Profile <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Option1</a>
                            </li>
                            <li>
                                <a href="#">Option1</a>
                            </li>
                            <li>
                                <a href="#">Option1</a>
                            </li>
                        </ul>
                    </li> -->
                    <li class="">
                        <a href="{% url 'applogin:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
    
            </div>
        </div>
    </nav>
        
    {% block body %}
    {% endblock %}
    
    </body>
</html>

principalhome/templates/principalhome/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-3 col-sm-9">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-3">{{ field.label_tag }}</label>
		<div class="col-sm-9">{{ field }}</div>
	</div>

{% endfor %}

principalhome/templates/principalhome/homepage.html
{% extends 'principalhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Welcome {{ bundle.user }}</h1>
            <h4>Here's an overview of {{ bundle.school }}</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Stats</th>
                    <th class="text-center text-uppercase">Detail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>No. of students registered: </td>
                    <td>{{ bundle.students }}</td>
                </tr>
                <tr>
                    <td>No. of teachers:</td>
                    <td>{{ bundle.teachers }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div> 

{% endblock %}

principalhome/templates/principalhome/students.html
{% extends 'principalhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Students</h1>
            <h4>Class-wise list of students currently registered</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Class</th>
                    <th class="text-center text-uppercase"># Students</th>
                </tr>
            </thead>
            <tbody>
                {% for clss, count in class_dict.items %}
                    <tr>
                        <td><a href="{% url 'principalhome:class_students' clss %}">{{ clss }}</a></td>
                        <td>{{ count }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

principalhome/templates/principalhome/students_detail.html
{% extends 'principalhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Student Details</h1>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Stats</th>
                    <th class="text-center text-uppercase">Detail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name</td>
                    <td>{{ student }}</td>
                </tr>
                <tr>
                    <td>Date of Birth</td>
                    <td>{{ student.date_of_birth }}</td>
                </tr>
                <tr>
                    <td>Admission Date</td>
                    <td>{{ student.admission_date }}</td>
                </tr>
                <tr>
                    <td>Enrolment No</td>
                    <td>{{ student.enrolment_no }}</td>
                </tr>
                <tr>
                    <td>Class</td>
                    <td>{{ student.study }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

principalhome/templates/principalhome/students_index.html
{% extends 'principalhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>{{ clss }}</h1>
            <h4>.....</h4>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Name</th>
                    <th class="text-center text-uppercase"> Enrolment No. </th>
                </tr>
            </thead>
            <tbody>
                {% for student in class_students %}
                    <tr>
                        <td><a href="{% url 'principalhome:students_detail' clss student.name_to_url %}">{{ student }}</a></td>
                        <td>{{ student.enrolment_no }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

principalhome/templates/principalhome/teachers.html
{% extends 'principalhome/base.html' %}

{% block body %}
<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Teachers</h1>
            <h4>List of teachers currently registered</h4>
    </div>
</div>
<div class="container">
    {% if teachers %}
        <div class="col-sm-offset-1 col-sm-8">
            <table class="table table-striped table-bordered text-center">
                <thead>
                    <tr>
                        <th class="text-center text-uppercase">Name</th>
                        <th class="text-center text-uppercase">Subject</th>
                    </tr>
                </thead>
                <tbody>
                    {% for teacher in teachers %}
                        <tr>
                            <td><a href="{% url 'principalhome:teachers_detail' teacher.name_to_url %}">{{ teacher }}</a></td>
                            <td>{{ teacher.subject }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No teachers registered yet.
    {% endif %}
</div>

{% endblock %}

principalhome/templates/principalhome/teachers_detail.html
{% extends 'principalhome/base.html' %}

{% block body %}

<div style="padding-top: 10px; padding-bottom: 10px">
    <div class="container" style=" height: 120px; background-color: lightcyan">
            <h1>Teacher Details</h1>
    </div>
</div>

<div class="container">
    <div class="col-sm-offset-1 col-sm-8">
        <table class="table table-striped table-bordered text-center">
            <thead>
                <tr>
                    <th class="text-center text-uppercase">Stats</th>
                    <th class="text-center text-uppercase">Detail</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Name</td>
                    <td>{{ teacher }}</td>
                </tr>
                <tr>
                    <td>Date of Birth</td>
                    <td>{{ teacher.date_of_birth }}</td>
                </tr>
                <tr>
                    <td>Joining Date</td>
                    <td>{{ teacher.joining_date }}</td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td>{{ teacher.email }}</td>
                </tr>
                <tr>
                    <td>Phone No.</td>
                    <td>{{ teacher.phone }}</td>
                </tr>
                <tr>
                    <td>Class Teacher</td>
                    <td>{{ teacher.is_class_teacher }}</td>
                </tr>
                <tr>
                    <td>Subject</td>
                    <td>{{ teacher.subject }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}